# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: compile with Gradle
      run: ./gradlew compileJava

  Test:
    runs-on: ubuntu-latest
    needs: Compile
    steps:
    - uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test
    - name: upload all test report DIR
      uses: actions/upload-artifact@v2
      with:
        name: testReport
        path: build/reports/

    Assemble:
      runs-on: ubuntu-latest
      needs: Test
      steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Assemble jar file
        run: ./gradlew assemble
      - uses: actions/upload-artifact@v2
        with:
          name: buildJar
          path: build/libs/*.jar